### PR TITLE
Fix incorrect wg usage

### PR DESCRIPTION
**Pull request by cwdsuzhou**
```
defer(){
   wg.Wait()
}
```
would bring extra load, we could use `wg.Wait` outside the `foreach`

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
@cwdsuzhou i didn't quite get this fix, the ```wg.Wait``` already outside the ```for``` loop.

**Comment by cwdsuzhou** [comment]
> @cwdsuzhou i didn't quite get this fix, the `wg.Wait` already outside the `for` loop.

defer would bring extra cost. Since we could directly use wait.Wait, defer is unnecessary

**Pull request closed without merging**
