### PR TITLE
-Fix dependency and import path errors

### PR DESCRIPTION
**Pull request by wgliang**
Fix dependency and import path errors

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
@wgliang we have a work in progress PR raised for this.
[Refer this pull request](https://github.com/kubernetes-sigs/poseidon/pull/17)

It addresses all the import and dependency issues.
You can fetch the above PR and check.

@dhilipkumars

**Comment by dhilipkumars** [comment]
@wgliang Do we need this PR now? as mentioned we have handled this with the other one.  It would be great if you could verify if the new codebase.  Thanks

**Comment by wgliang** [comment]
@shivramsrivastava @dhilipkumars 
I have merged the submission of this PR(#17 ), in addition we need to submit a symbolic link file to the package below k8s.io/pkg to support the access of k8s.io/pkg/firmament.

**Comment by shivramsrivastava** [comment]
@wgliang Sorry I am not able to get your point.
Why we need a symbolic link under k8s.io/pkg?

**Comment by wgliang** [comment]
Sorry, it is my environment error and I will close this PR.

**Pull request closed without merging**
