### PR TITLE
Increasing the default timeout to 60m for the local E2E tests

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
Increasing the default timeout to 60m for the local E2E tests

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
@hanxiaoshuai This issue is already addressed in PR #80 
This code is already merged.

**Comment by shivramsrivastava** [comment]
@hanxiaoshuai ok you have done it for the local e2e test script.

**Comment by hanxiaoshuai** [comment]
@shivramsrivastava There two shell. test/e2e-poseidon-gce.sh and test/e2e-poseidon-local.sh. It seems that both of them should be increasing the default timeout

**Pull request merged**
