### PR TITLE
Fix hack/verify-go(lint,vet).sh

### PR DESCRIPTION
**Pull request by shashidharatd**
This fix along with test-infra [fix](https://github.com/kubernetes/test-infra/pull/7669) fix should fix the current issues faced by all pr's in this repo.

/cc @dhilipkumars @shivramsrivastava @deepak-vij @m1093782566

### CODE REVIEW

**Comment by m1093782566** [comment]
LGTM

But, I would strongly suggest create the build test job to avoid such failure.

**Comment by shivramsrivastava** [comment]
@shashidharatd Thanks for the changes.
We were using dep dependency manager initially, but it was broken.
The go-client library is yet to support the 'dep'.
See this [link](https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep-not-supported-yet)
I see you have moved the dependency management back to dep.
Is this really needed cant we use godep instead?

**Comment by shashidharatd** [comment]
@shivramsrivastava, AFAIK the reason for not using `dep` is not valid one.
PTAL at https://github.com/kubernetes/kops/blob/master/Gopkg.toml, they too use `go-client` but use `dep` for package dependency management. Anyway, its not good to migrate `dep` in this pr.
So i will revert the changes and try adding `golint` to vendor code using godep itself.

**Comment by dhilipkumars** [comment]
@shashidharatd this CI image has go 1.9, our hack script expects 1.9.1 and above, shiva had relaxed this rule relectly in other PR.

**Comment by shashidharatd** [comment]
> @shashidharatd this CI image has go 1.9, our hack script expects 1.9.1 and above, shiva had relaxed this rule relectly in other PR.

yeah found that and pushed a commit to lower the check to go1.8.3, seems like container image we are using has go1.9

**Pull request merged**
