### PR TITLE
Adding Taints & Toleration Feature, few performance improvements and minor bug fixes

### PR DESCRIPTION
**Pull request by shivramsrivastava**
This PR addresses the issue #52 along with the following improvements and few bug fixes.

 - [x] Adding QPS and Burst to the Poseidon client configs
 - [x] Bind call is now multi go-routined 
 - [x] Added the Taints and Toleration feature
 - [x] Added test cases for Taints and Toleration feature and Pod affinity and Anti-affinity symmetry case.
 - [x] Minor bug fixes in the Pod affinity test case which were failing earlier.
 - [x] Fixed a bug which was wrongly processing the pods as pending pods instead as pod updated.

### CODE REVIEW

**Comment by BenTheElder** [comment]
I'm not aware of any relevant changes related to cluster spin-up. That's been pretty much left alone lately. I notice you're using `--extract=ci/latest` though, which means you get a bleeding edge kubernetes build. It's possible the scripts are broken in that build.

**Comment by shivramsrivastava** [comment]
@BenTheElder Most of the CI jobs are using the same image 'ci/latest'.
Only few are using the other verisons.
If the scripts are broken, others will also have the same issue.

```
W0810 23:40:53.859] ERROR: (gcloud.compute.ssh) Could not fetch resource:
W0810 23:40:53.859]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:40:53.860] 
W0810 23:40:59.503] ERROR: (gcloud.compute.ssh) Could not fetch resource:
W0810 23:40:59.504]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:40:59.504] 
W0810 23:41:05.135] ERROR: (gcloud.compute.ssh) Could not fetch resource:
W0810 23:41:05.135]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:41:05.135] 
W0810 23:41:10.753] ERROR: (gcloud.compute.ssh) Could not fetch resource:
W0810 23:41:10.753]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:41:10.754] 
W0810 23:41:16.408] ERROR: (gcloud.compute.ssh) Could not fetch resource:
W0810 23:41:16.408]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:41:16.409] 
W0810 23:41:22.104] ERROR: (gcloud.compute.ssh) Could not fetch resource:
W0810 23:41:22.104]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:41:22.104] 
I0810 23:41:22.205] Copying 'kern kube-apiserver kube-apiserver-audit kube-scheduler rescheduler kube-controller-manager etcd etcd-events glbc cluster-autoscaler kube-addon-manager fluentd startupscript docker kubelet supervisor/supervisord supervisor/kubelet-stdout supervisor/kubelet-stderr supervisor/docker-stdout supervisor/docker-stderr' from e2e-301-7de10-master
W0810 23:41:22.755] ERROR: (gcloud.compute.instances.get-serial-port-output) Could not fetch serial port output: The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:41:23.415] ERROR: (gcloud.compute.scp) Could not fetch resource:
W0810 23:41:23.415]  - The resource 'projects/k8s-jkns-gke-reboot-1-4/zones/us-central1-b/instances/e2e-301-7de10-master' was not found
W0810 23:41:23.415] 
```

**Comment by BenTheElder** [comment]
Sure, but that makes sense for jobs that are testing kubernetes itself, most of them are.

**Comment by deepak-vij** [comment]
Hi Dujun, yes that is the plan. Once this PR merges, Shiva will reach out to you for cutting a release. We had to delay our 0.4 release as we ran into several performance bottlenecks as well as stability issues. Hopefully, everything is fixed now and ready to go.

**Comment by m1093782566** [comment]
No worries, @hanxiaoshuai will do your favor.

**Pull request merged**
