### PR TITLE
E2E test case for CPU cost model

### PR DESCRIPTION
**Pull request by m1093782566**
/cc @deepak-vij 

NOTE: we will cover RAM cost model in follow-ups.

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
@m1093782566 looks like verify test itself is failing.
There are no vendor changes in this PR.
There is more vendor dependency injected by this change.

From the code changes, it looks like you have tried to bring in most of the changes into our framework package, but there are other dependent packages which are missing.

If we try to bring in the e2e test case as-is from the default scheduler e2e code,
we will have to end up vendoring many packages or the whole k8s code.

We also faced many issues like this when we started with E2E tests, trying to vendor the e2e/framework package didn't work.

So we worked from our e2e test cases and pulled only the essential packages and methods.
Say if we need only one method from a package we could very well copy in our framework code rather than vendoring it, provided those package which it refers are already available in our vendor. 
If they are not available then we will vendor only those packages.
This will reduce the vendor dependency to a great extent.

**Comment by shivramsrivastava** [comment]
@m1093782566 The test is failing because the filler pods are not getting scheduled.
The other pods from the previous tests are still running.

And this test only calculates the remaining CPU and not the MEM.
Why are we considering only the limit of CPU and not MEM in this test case?
Need to check why those pods are not getting schedules on those nodes?
You can use a more verbose output from Poseidon you can add '--v=3' to the container cmd in the Poseidon deployment yaml.

**Comment by m1093782566** [comment]
@shivramsrivastava 

> The test is failing because the filler pods are not getting scheduled.
The other pods from the previous tests are still running.

How to delete them?

**Comment by deepak-vij** [comment]
Let us resolve this issue as soon as possible. Thanks.

**Comment by m1093782566** [comment]
@shivramsrivastava 

> The test is failing because the filler pods are not getting scheduled.
The other pods from the previous tests are still running.

Per @deepak-vij, we just set up a totally new cluster for each run, so why there are some legacy pods?

**Comment by m1093782566** [comment]
@deepak-vij @shivramsrivastava 

Interesting! CI check are green now. PTAL.

THANKS!

**Comment by deepak-vij** [comment]
Dujun, let us chat tonight what change you made in order to make this work. I spoke to Shiva on this. we are suspecting that there might be an issue with the pod "delete" logic which Shiva wrote for cleaning up resources after each e2e test. Let us talk tonight to make sure we have really resolved this issue permanently.

**Comment by m1093782566** [comment]
@deepak-vij 

Sounds fair. BTW, I find master node will never be considered during scheduling.

```
I0515 03:11:28.254] Found 4 node(s).
I0515 03:11:28.415] NAME                             STATUS                     ROLES     AGE       VERSION
I0515 03:11:28.416] e2e-69-7de10-master              Ready,SchedulingDisabled   <none>    34s       v1.11.0-alpha.2.460+dc62a73742e42a
I0515 03:11:28.416] e2e-69-7de10-minion-group-3d7g   Ready                      <none>    39s       v1.11.0-alpha.2.460+dc62a73742e42a
I0515 03:11:28.416] e2e-69-7de10-minion-group-98th   Ready                      <none>    39s       v1.11.0-alpha.2.460+dc62a73742e42a
I0515 03:11:28.416] e2e-69-7de10-minion-group-zj47   Ready                      <none>    39s       v1.11.0-alpha.2.460+dc62a73742e42a
```

**Comment by shivramsrivastava** [comment]
@m1093782566 Can you please squash the commits.

**Comment by m1093782566** [comment]
@shivramsrivastava @deepak-vij 

Commits are squashed now. PTAL.

**Comment by shivramsrivastava** [comment]
Thanks @m1093782566 .

I will approve this, But we need to address the following issues.
We can raise separate issues.

1) Why are the pods still running after a test is completed?
     All the test call's 'Delete' ( for its kind ) after each test run, but still, the pods are in running state.
      except for the first test case, which is a simple pod deployment. Need to investigate this issue.

**Comment by m1093782566** [comment]
Sounds fair. We can track it.

**Pull request merged**
