### PR TITLE
Implement Verify Test 

### PR DESCRIPTION
**Pull request by dhilipkumars**
* gofmt - all the files
* golint - all the files
* fix imports 
* Added the verify script for below tests
  * verify-boilerplate.sh
  * verify-godeps.sh
  * verify-gofmt.sh
  * verify-golint.sh
  * verify-govet.sh
Currently we skip golint (internally)  our source code as it needs fixing, we should re-enable it after the errors have been fixed.

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
Thanks.

/lgtm

**Comment by shivramsrivastava** [comment]
@ICGog

**Comment by shivramsrivastava** [comment]
I have verified the changes.

/approve

**Comment by ICGog** [comment]
@dhilipkumars Can you please explain why we had to bring in the hack directory?

**Comment by deepak-vij** [comment]
I am assuming this is somewhat of a convention in Kubernetes community to have a temporary directory for storing commonly used scripts in, I think.

@dhilipkumars Could you please confirm it. Thanks.

**Comment by dhilipkumars** [comment]
@ICGog Yes, that contains all the makefiles and verification script, its basically like a framework verification script, this is adopted from kubernetes/kubernetes to other projects also eg: [federation](https://github.com/kubernetes/federation), [kops](https://github.com/kubernetes/kops) , etc., all have similar hack directory.

Currently we have these verification steps, (we may add a couple more)
```
verify-all.sh  verify-boilerplate.sh  verify-godeps.sh  verify-gofmt.sh  verify-golint.sh  verify-govet.sh  verify-linkcheck.sh
```
but kubernetes has this many, we dont need most of them. 
```
verify-all.sh                 verify-cloudprovider-gce.sh        verify-generated-files-remake.sh  verify-gofmt.sh        verify-no-vendor-cycles.sh   verify-symbols.sh
verify-api-groups.sh          verify-codegen.sh                  verify-generated-protobuf.sh      verify-golint.sh       verify-openapi-spec.sh       verify-test-images.sh
verify-api-reference-docs.sh  verify-description.sh              verify-generated-runtime.sh       verify-govet.sh        verify-pkg-names.sh          verify-test-owners.sh
verify-bazel.sh               verify-flags-underscore.py         verify-generated-swagger-docs.sh  verify-import-boss.sh  verify-readonly-packages.sh
verify-boilerplate.sh         verify-generated-device-plugin.sh  verify-godep-licenses.sh          verify-imports.sh      verify-staging-godeps.sh
verify-cli-conventions.sh     verify-generated-docs.sh           verify-godeps.sh                  verify-linkcheck.sh    verify-swagger-spec.sh
```

**Pull request merged**
