### PR TITLE
Fixed a bug in the nodeselector sort method

### PR DESCRIPTION
**Pull request by shivramsrivastava**
/assign @deepak-vij 
@m1093782566 

This change addressed an issue with the nodeselector sort function.
After this fix, the PR #73 should PASS.

### CODE REVIEW

**Comment by shivramsrivastava** [comment]
I looked into the nodeselector test case, it looks like this PR will not fix that issue.
Because only one nodeselctor is passed in all the test cases, and the bug in sort has no effect in that case.

**Comment by m1093782566** [comment]
> Because only one nodeselctor is passed in all the test cases, and the bug in sort has no effect in that case.

Agree. But I think we can let this PR in because it should resolve some bugs.

**Pull request merged**
