### PR TITLE
Fixing the Poseidon-Verify error, missing bc command

### PR DESCRIPTION
**Pull request by shivramsrivastava**
The Poseidon-verify script was failing because of the missing bc command.
This fix refreshes the script file from the k/k repo.
Now the bc command is replaced with 'awk' command.

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@shivramsrivastava 

could you also relax the verify check to go1.9 and above instead specifically looking for go1.9.1 please?
```
W0410 07:06:47.890] Detected go version: go version go1.9 linux/amd64.
W0410 07:06:47.892] Kubernetes requires go1.9.1 or greater.
W0410 07:06:47.893] Please install go1.9.1 or later.
```

**Comment by shivramsrivastava** [comment]
@dhilipkumars it seems to be some other issue with verify.
Anyways I have changed the minimum version as per your suggestion.
please approve it.

**Comment by m1093782566** [comment]
```
410 08:24:52.360] hack/make-rules/../../hack/verify-golint.sh
I0410 08:24:52.360] hack/make-rules/../../hack/verify-govet.sh
```

I am working on a PR(#28) to fix the golint error.

**Comment by dhilipkumars** [comment]
@shivramsrivastava && @m1093782566 , I'm going to check if the docker image in which the CI is running has any problem with these failures.

**Comment by m1093782566** [comment]
@dhilipkumars 

That would be great. BTW, I would suggest disable the `pull-poseidon-verify ` for now since there are a bunch of `govet` and `golint` verifies to be fixed.

**Comment by deepak-vij** [comment]
Hi Dujun, instead of disabling the Verify job at this time, my recommendation would be to wait for the Verify job to get fixed. Dhilip & Shiva are very diligently working on resolving this issue. This particular issue is due to the package imports in the new Kubernetes-SIGs org. This new org resides outside the original Kubernetes org. We are the very first incubation repo in this org, guinea pigs, to resolve all such issues. We are hoping to get this resolved soon.

Once resolved, we can retest your PR and hopefully successfully merge it. Thanks.

**Comment by m1093782566** [comment]
Hi deepak, thanks for clarification. BTW, I am working on also working on fix golint errors. Please feel free to let me know if I can do some help :)

**Comment by deepak-vij** [comment]
Thanks Dujun, very much appreciate your help. As Dhilip is working towards resolving the Verify job issue and Shiva is working towards automating e2e testing, it would be really great if you can start adding comments in Poseidon codebase as you start understanding the code. Feel free to reach out to us if you need any clarifications or any other help you need while incorporating comments in the codebase.

As a matter fact, originally you yourself volunteered to do this exercise. Thanks.

Deepak

**Comment by m1093782566** [comment]
Okay!

**Comment by shashidharatd** [comment]
The needed commit in this pr is merged with this [pr](https://github.com/kubernetes-sigs/poseidon/pull/31/commits). The other commits are no longer required. Hence closing this pr. Thanks !
/close
@shivramsrivastava please feel free to reopen if i had misrepresent it.

**Pull request closed without merging**
