### PR TITLE
Make poseidon release

### PR DESCRIPTION
**Pull request by m1093782566**
This PR automatically make poseidon release in bazel way - in kubernetes format.

Type command 

```
make quick-release
```

will create a poseidon release. Then, we would see release images and release packages in the `_output` directory of the root directory.

NOTE: It consists of many changes and we can clean it clean in follow-ups.

@shashidharatd I guess we may need to change bazel to gazel in order to support the BUILD format:

```
load("@io_kubernetes_build//defs:build.bzl", "release_filegroup")
load("@io_kubernetes_build//defs:pkg.bzl", "pkg_tar")
```

I changed the {update, verify}-bazel.sh as well to fix the CI failures.

### CODE REVIEW

**Comment by m1093782566** [comment]
@shivramsrivastava @deepak-vij 

Glad to tell you that all CI checks are GREEN now!

We can review this PR and let this PR in if you are happy with these changes :)

**Comment by shivramsrivastava** [comment]
@m1093782566 Thanks for this PR.

I would like to know what this PR does? How to test it?
As per our discussion today morning, we planned to revert back to PR #41, removing the bazel build for containers, since its too complex. Does this PR still use the same old makefile way to build and release the Poseidon containers?

PR #41 is simple, and if it does the job of building the release and container it will be good and we don't need this huge change.

@shashidharatd @deepak-vij

**Comment by m1093782566** [comment]
@shivramsrivastava 

> I would like to know what this PR does? How to test it?

Basically, this PR can automatically make a Poseidon release by simply typing `make quick-release`.

> As per our discussion today morning, we planned to revert back to PR #41, removing the bazel build for containers, since its too complex. Does this PR still use the same old makefile way to build and release the Poseidon containers?

#41 does not work properly now. I removed the bazel-related changes in this PR so that it uses the old and Makefile way to build and release the Poseidon containers.

> PR #41 is simple, and if it does the job of building the release and container it will be good and we don't need this huge change.

Let's keep working in this PR and I can reduce the unnecessary files to make this PR look simpler. Anyway, this PR works now.

**Comment by shivramsrivastava** [comment]
@m1093782566 i am getting this error.

```
$ sudo make quick-release
+++ [0425 05:39:36] Verifying Prerequisites....
+++ [0425 05:39:36] Building Docker image kube-build:build-5bf7ca0924-5-v1.9.3-1
+++ [0425 05:39:54] Syncing sources to container
+++ [0425 05:39:57] Running build command...
Skipping generated files....
+++ [0425 05:39:58] Building the toolchain targets:
    github.com/kubernetes-sigs/poseidon/vendor/k8s.io/kubernetes/hack/cmd/teststale
+++ [0425 05:39:59] Building go targets for linux/amd64:
    cmd/poseidon
Skipping generated files....
+++ [0425 05:40:16] Building the toolchain targets:
    github.com/kubernetes-sigs/poseidon/vendor/k8s.io/kubernetes/hack/cmd/teststale
+++ [0425 05:40:16] Building go targets for linux/amd64:
    test/e2e/e2e.test
Skipping generated files....
+++ [0425 05:40:35] Building the toolchain targets:
    github.com/kubernetes-sigs/poseidon/vendor/k8s.io/kubernetes/hack/cmd/teststale
+++ [0425 05:40:35] Building go targets for linux/amd64:
    vendor/github.com/onsi/ginkgo/ginkgo
+++ [0425 05:40:38] Syncing out of container
+++ [0425 05:40:40] Building tarball: src
+++ [0425 05:40:41] Building tarball: server linux-amd64
!!! [0425 05:40:41] git version information missing; cannot create Docker tag
!!! [0425 05:40:41] previous tarball phase failed
Makefile:406: recipe for target 'quick-release' failed
make: *** [quick-release] Error 1
```

**Comment by m1093782566** [comment]
Should export the `KUBE_GIT_VERSION` firstly, for example,

```
KUBE_GIT_VERSION=v1.1.0-alpha.0.6+84c76d1142ea4d
```

**Comment by m1093782566** [comment]
I am trying to find a better way to generate the random version string, e.g. pick the commit id of git HEAD. WDYT?

**Comment by shivramsrivastava** [comment]
It that a manual step to set the ```KUBE_GIT_VERSION```?

**Comment by m1093782566** [comment]
@shivramsrivastava 

I sent a fix in #45, PTAL.

**Pull request merged**
