### PR TITLE
add node affinity and node selector design doc

### PR DESCRIPTION
**Pull request by hpejustin**
move design doc of “Node Selector and Node Affinity Design for Firmament/Poseidon Scheduler” from Google doc(https://docs.google.com/document/d/1Qf_-g4FRL-nlHgnQnENw4iTjIE3FLQPXf__N0fxug78/edit#) to Markdown style according to issue #106

### CODE REVIEW

**Comment by hpejustin** [comment]
@deepak-vij , please review

**Comment by shivramsrivastava** [comment]
@hpejustin This below test keeps failing.
I know this is not related to this PR.
But it will be good if you can help us resolve this?
Can you please raise an issue and work on this?

```
I0708 16:20:57.854] [Fail] Poseidon Poseidon [Pod Affinity and Anti-Affinity] [It] validates scheduler respect's a pod-anti-affinity with hard constraint and affinity soft constraint 
```

**Comment by m1093782566** [comment]
> @m1093782566: you can't request testing unless you are a kubernetes-sigs member.

@bentheelder I think I need your help again.

**Comment by hpejustin** [comment]
I think the PR owner can trigger this by themselves, as the e2e test ci-poseidon-e2e-gce may failed at the first time but success at the next time.

**Comment by BenTheElder** [comment]
side note: normally jobs named `ci-*` run after merge or just periodically against the repo, `pull-*` run on PRs.. we should probably rename `ci-poseidon-e2e-gce` to `pull-poseidon-e2e-gce` for consistency.

**Comment by BenTheElder** [comment]
filing an issue to get this fixed, sorry about that :(
https://github.com/kubernetes members should be able to trigger testing here

**Comment by deepak-vij** [comment]
@hpejustin the MD format looks fine except for minor correction.  Last two items are sub-sections of "nodeAffinity Approach" section. It currently shows up as separate section underneath "Key Processing Design Details" section. 

	Key Processing Design Details 
	nodeSelector Approach
	nodeAffinity Approach
	Expressing Hard Constraints
	Expressing Soft Constraints

**Comment by m1093782566** [comment]
@hpejustin better to squeeze commits.

**Pull request merged**
